### ISSUE TITLE
Files are not displaying or downloading in the `recordings.html` file.

### ISSUE THREAD

**Issue by Crazygamerxs** [jerinpious/CSCN72030-Sec2-Group1#8]
Details:
- File Structure: Confirm that the files are in the expected location relative to the HTML file.
- File Formats: Ensure that the file formats are supported for display or download.
- File Paths: Double-check that the file paths in the HTML match the actual file locations.
- Links: Verify that the links to the files are correctly formatted.

Steps to Reproduce:
1. Open `recordings.html` in a browser.
2. Observe that files are not displayed or not downloadable.

**Comment by jerinpious** [comment]
Stored the image paths in a variable and passed it to the html for displaying the images
